# Generated by Django 4.0.3 on 2022-06-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
