# Generated by Django 4.0.3 on 2022-06-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_loan_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Available to borrow'), ('approved', 'Available to borrow')], default='approved', max_length=8),
            preserve_default=False,
        ),
    ]
