# Generated by Django 4.0.3 on 2022-06-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_salarycategory_alter_loan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetype',
            name='salaryCategory',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Not Fixed', 'Not Fixed')], default='Fixed', max_length=9),
        ),
        migrations.DeleteModel(
            name='SalaryCategory',
        ),
    ]
