# Generated by Django 4.0.3 on 2022-07-02 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_attendance_options_rolesalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesalary',
            name='employeeType',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app.employeetype'),
        ),
    ]
