# Generated by Django 4.0.3 on 2022-07-10 13:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_rolesalary_employeetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', upload_to=app.models.upload_to),
        ),
    ]
