# Generated by Django 4.0.3 on 2022-07-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_attendance_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
