# Generated by Django 4.0.3 on 2022-07-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loanrecovery',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='measurecriteria',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rolesalary',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salary',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
    ]
