# Generated by Django 4.0.3 on 2022-07-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_attendance_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
    ]
