# Generated by Django 4.0.3 on 2022-07-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_reversionrevision_reversionversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee',
        ),
    ]
