# Generated by Django 4.0.3 on 2022-07-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_user_employee_alter_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='issue_date',
            new_name='apply_date',
        ),
    ]
