# Generated by Django 4.0.3 on 2022-07-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_issue_date_loan_apply_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': [('can_approve_loan', 'Can approve or reject loan application')]},
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
