# Generated by Django 4.0.3 on 2022-07-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_loan_options_alter_dailywork_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': [('approveLoan_loan', 'Can approve or reject loan application')]},
        ),
    ]
