# Generated by Django 4.0.3 on 2022-07-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': [('approveLoan_loan', 'Can approve or reject loan application'), ('viewLoanApplicationStatus_loan', 'Can view loan application status')]},
        ),
    ]
