# Generated by Django 4.0.3 on 2022-07-18 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_loan_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chemical',
        ),
    ]
