# Generated by Django 4.0.6 on 2022-07-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_salary_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
