# Generated by Django 4.0.6 on 2022-07-28 01:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_salary_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 28, 1, 40, 9, 459178, tzinfo=utc)),
        ),
    ]
