# Generated by Django 4.0.6 on 2022-07-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_employeetype_salarycategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='employeeType',
            new_name='employee_type',
        ),
    ]
