# Generated by Django 4.0.6 on 2022-07-30 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_role_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='app.role'),
            preserve_default=False,
        ),
    ]
