# Generated by Django 4.0.6 on 2022-08-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_employee_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'permissions': [('generate_salary', 'Can generate salary'), ('pay_salary', 'Can pay salary')]},
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
