# Generated by Django 4.0.6 on 2022-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_salary_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetype',
            name='salaryCategory',
            field=models.CharField(choices=[('Not Fixed', 'Not Fixed')], default='Not Fixed', max_length=9),
        ),
    ]
