# Generated by Django 4.0.6 on 2022-08-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_employee_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Unit',
        ),
        migrations.RenameField(
            model_name='productprice',
            old_name='product',
            new_name='unit',
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('unit', 'department', 'criteria')},
        ),
    ]
