# Generated by Django 4.0.6 on 2022-08-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_rename_productprice_unitprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurecriteria',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
