# Generated by Django 4.0.6 on 2022-08-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_rename_group_usergroup_alter_usergroup_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
