# Generated by Django 4.0.6 on 2022-08-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetype',
            name='salaryCategory',
        ),
    ]
