# Generated by Django 4.0.6 on 2022-08-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='end',
            field=models.TimeField(),
        ),
    ]
