# Generated by Django 4.0.6 on 2022-08-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_remove_salarygeneration_generate_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
