# Generated by Django 4.0.6 on 2022-08-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_dailywork_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'permissions': [('generateReport_attendance', 'Can generate attendance report')]},
        ),
        migrations.AlterModelOptions(
            name='dailywork',
            options={'ordering': ['date'], 'permissions': [('generateReport_dailywork', 'Can generate daily work report')]},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'permissions': [('generate_salary', 'Can generate salary'), ('pay_salary', 'Can pay salary'), ('generateReport_salary', 'Can generate salary report')]},
        ),
    ]
