# Generated by Django 4.0.6 on 2022-08-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_dailywork_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='apply_date',
            field=models.DateField(),
        ),
    ]
