# Generated by Django 4.0.6 on 2022-08-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_loan_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrecovery',
            name='recovery_date',
            field=models.DateField(),
        ),
    ]
