# Generated by Django 4.0.6 on 2022-08-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_loanrecovery_recovery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='date',
            field=models.DateField(),
        ),
    ]
