# Generated by Django 4.0.6 on 2022-08-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_dailywork_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'usergroup', 'verbose_name_plural': 'usergroups'},
        ),
    ]
