# Generated by Django 4.0.6 on 2022-08-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_usergroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanrecovery',
            options={'permissions': [('generateReport_loanrecovery', 'Can generate loan recovery report')]},
        ),
    ]
